name: action lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

concurrency:
  group: action-lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1.71.0
        with:
          fail_level: warning
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  ghalint:
    name: ghalint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b2b4a5ef441beae1e19ff3862ec # v3.1.1
        with:
          aqua_version: v2.45.0
      - run: ghalint run
