name: action lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

concurrency:
  group: action-lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1.71.0
        with:
          fail_level: warning
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  ghalint:
    name: ghalint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      GHALINT_VERSION: v1.5.5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - run: |
          VERSION="${GHALINT_VERSION#v}"
          curl -sSfL "https://github.com/suzuki-shunsuke/ghalint/releases/download/${GHALINT_VERSION}/ghalint_${VERSION}_linux_amd64.tar.gz" | tar xz -C /usr/local/bin
          ghalint run
